---
- name: do apt-get update
  apt:
    update_cache: yes

- name: install docker prequesites
  apt:
    name: "{{ packages }}"
  vars:
    packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

- name: download docker gpg
  apt_key:
     url: https://download.docker.com/linux/ubuntu/gpg
     state: present


- name: add docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
  tags: repo3

- name: do apt-get update
  apt:
    update_cache: yes
  tags: up

- name: install dockers
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  tags: docker
